# Site settings
title: Whatever IT Takes!
#email: shankx@mac.com
description: > # this means to ignore newlines until "baseurl:"
  Whatever IT Takes describes the journey of a web developer who is determined to achieve mastery in the art of programming.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://shankx50.github.io" # the base hostname & protocol for your site
twitter_username: ShankarPoncelet
github_username:  shankx50

# Build settings
markdown: kramdown
